import Database from "better-sqlite3";
const db = new Database("E:\\sag\\dist\\builds\\sag-20260813-171645\\data\\sag.db");
const ee = db.prepare("DELETE FROM event_entities WHERE event_id IN (SELECT id FROM events WHERE source_id NOT IN (SELECT id FROM sources)) RETURNING event_id").all();
console.log("deleted event_entities:", ee.length);
const ev = db.prepare("DELETE FROM events WHERE source_id NOT IN (SELECT id FROM sources) RETURNING id").all();
console.log("deleted events:", ev.length);
const en = db.prepare("DELETE FROM entities WHERE source_id NOT IN (SELECT id FROM sources) RETURNING id").all();
console.log("deleted entities:", en.length);
db.close();
console.log("done. Run VACUUM next.");